### ISSUE TITLE
Invalid link in main README

### ISSUE THREAD

**Issue by fvanderbiest** [camptocamp/c2cgeoform#105]
The link to an example model in the first README sentence is invalid: it leads to https://github.com/camptocamp/c2cgeoform/blob/master/c2cgeoform/pully/model.py

"c2cgeoform is a framework easing the creation of web pages with forms. Users of c2cgeoform declaratively create models (**example**), from which the framework can create forms, views, lists, …"

**Comment by arnaud-morvan** [comment]
Link removed in branch getitfixed, will be merged soon.
