### ISSUE TITLE
Update Deform

### ISSUE THREAD

**Issue by tsauerwein** [camptocamp/c2cgeoform#43]
Once a new version of Deform is released, which contains this PR https://github.com/Pylons/deform/pull/243, we can do the following change in `views.py`:
https://github.com/camptocamp/c2cgeoform/blob/99555e6848f4adcde4172183928a58c1b2d401f8/c2cgeoform/views.py#L58

Replace

```
 except ValidationFailure, e:
    # FIXME see https://github.com/Pylons/deform/pull/243
    rendered = e.field.widget.serialize(
    e.field, e.cstruct, custom_data=custom_data)
```

with 

```
 except ValidationFailure, e:
    rendered = e.serialize(custom_data=custom_data)
```

**Comment by arnaud-morvan** [comment]
Done
