### ISSUE TITLE
[Demo] Links are dead

### ISSUE THREAD

**Issue by ponceta** [camptocamp/c2cgeoform#98]
http://mapfish-geoportal.demo-camptocamp.com/c2cgeoform/wsgi/fouille/form/

http://mapfish-geoportal.demo-camptocamp.com/c2cgeoform/wsgi/fouille/

Would be great to have a few printscreens?

**Comment by sbrunner** [comment]
New links:

https://geomapfish-demo.camptocamp.net/c2cgeoform/wsgi/fouille/form/

https://geomapfish-demo.camptocamp.net/c2cgeoform/wsgi/fouille/

:-)
